### ISSUE TITLE
Make `ClientConf` parameters optional.

### ISSUE THREAD

**Issue by whhe** [oceanbase/oblogclient#16]
We should allow users to configure these parameters in [ClientConf](https://github.com/oceanbase/oblogclient/blob/master/logproxy-client/src/main/java/com/oceanbase/clogproxy/client/config/ClientConf.java).

**Comment by longwithyou** [comment]
1

**Comment by whhe** [comment]
A case that will cause exception: one process create mutiple instances of LogProxyClient in one second, for now these client instances will contain the same ClientId, which is not allowed in oblogproxy and only one instance can connect successfully. 

I found this when testing the tutorial of Flink CDC connector, an etl job will always create mutiple instances of LogProxyClient. I temporarily fixed it by set different values to ClientId but it didn't solve the root problem. 

https://github.com/whhe/flink-cdc-connectors/blob/80f178f6b2cd9f5566454aadf838e55f47cd8784/flink-connector-oceanbase-cdc/src/main/java/com/ververica/cdc/connectors/oceanbase/source/OceanBaseRichSourceFunction.java#L292

Maybe this issue should be fixed sooner.
