### ISSUE TITLE
[Bug]: 断开连接时，clientid 无法断开

### ISSUE THREAD

**Issue by leilinen** [oceanbase/oblogclient#65]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Environment

```markdown
使用flink oceanbase cdc抽取oceanbase数据，当flink作业发生重启时，会出现clientid 重复导致oblogproxy挂掉。
flink 版本 1.13.5
oceanbase-cdc版本 2.3.0
oceanbase 版本  3.1.4
oblogclient 版本 1.0.5
oblogproxy 版本 1.0.3
```

### Fast Reproduce Steps

flink发生异常重启时，oblogclient 无法断开连接，导致duplication clientid error，然后oblogproxy会挂掉。

![image](https://user-images.githubusercontent.com/20055281/206993871-66d2c50f-b763-462a-a621-eaa636a7e772.png)

### Actual Behavior

oblogclient 应该断开连接，释放clientid。

**Comment by whhe** [comment]
Is there any messages about the connection exit in the flink log? Normally it will call the cancel function of `OceanBaseRichSourceFunction` and it will close the connection.

**Comment by leilinen** [comment]
升级oblogproxy版本到最新的版本，这个问题没有再出现。
