### ISSUE TITLE
springboot 报错  

### ISSUE THREAD

**Issue by joranbo** [oceanbase/oblogclient#78]
### Description

![image](https://github.com/oceanbase/oblogproxy/assets/29445870/e9da564f-3543-4e69-9b8e-e68263765626)
怎么解决

**Comment by whhe** [comment]
看起来是缺少 protobuf 包，或者 oblogclient 用的 protobuf 依赖版本和你的项目有冲突。如果是版本冲突，假如真的没有办法使用同一个版本的话，可能需要先对两个版本中的一个做 shade 操作。
